/* Users */
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('USERS:LIST');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('USERS:VIEW');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('USERS:EDIT');

/* Orders */
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('ORDERS:ADD');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('ORDERS:LIST');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('ORDERS:VIEW');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('ORDERS:EDIT');

/* Listings */
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('LISTINGS:ADD');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('LISTINGS:LIST');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('LISTINGS:VIEW');

/* Proposals */
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PROPOSALS:ADD');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PROPOSALS:LIST');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PROPOSALS:VIEW');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PROPOSALS:REPLY');

/* Payments */
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PAYMENTS:ADD');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PAYMENTS:LIST');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PAYMENTS:VIEW');
INSERT INTO SPA_PRIVILEGE ( NAME ) VALUES ('PAYMENTS:MANAGE');