INSERT INTO SPA_ROLE_PRIVILEGE (FK_ROLE_ID, FK_PRIVILEGE_ID)
SELECT (SELECT PK_ID FROM SPA_ROLE WHERE NAME_EN='Customer'), PK_ID FROM SPA_PRIVILEGE WHERE ACTION NOT LIKE '%ALL';

INSERT INTO SPA_ROLE_PRIVILEGE (FK_ROLE_ID, FK_PRIVILEGE_ID)
SELECT (SELECT PK_ID FROM SPA_ROLE WHERE NAME_EN='Admin'), PK_ID FROM SPA_PRIVILEGE WHERE ACTION LIKE '%ALL';

INSERT INTO SPA_ROLE_PRIVILEGE (FK_ROLE_ID, FK_PRIVILEGE_ID)
SELECT (SELECT PK_ID FROM SPA_ROLE WHERE NAME_EN='Tester'), PK_ID FROM SPA_PRIVILEGE WHERE ACTION LIKE '%ALL';

INSERT INTO SPA_ROLE_PRIVILEGE (FK_ROLE_ID, FK_PRIVILEGE_ID)
SELECT (SELECT PK_ID FROM SPA_ROLE WHERE NAME_EN='Developer'), PK_ID FROM SPA_PRIVILEGE WHERE ACTION LIKE '%ALL';